name: Update Docker
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1,15 * *'
jobs:
  build_and_push_image:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: profiq/docker-node-npm-python-pip-serverless-gcloud:latest
